### DISCUSSION TITLE
Why does reviews.apache.org use an old version of Review Board?

### DISCUSSION THREAD

**Discussion by linghengqian** [apache/infrastructure-ideas#8] [Q&A] [answered]
- Out of curiosity, I noticed that https://reviews.apache.org is using Review Board 2.5.9, which was released on February 15, 2017. The interface seems a bit counter-intuitive.
- ![image](https://github.com/user-attachments/assets/0ad7c4f6-5c9f-4d60-8c0c-afe584c1eb99)
- I wonder why https://reviews.apache.org/ uses an old version of Review Board? I started a Review Board instance on `localhost:80` using the Docker Compose file from https://github.com/reviewboard/reviewboard/blob/release-7.0.2/contrib/docker/examples/docker-compose.postgres.yaml , and it looks like there are a lot of UI improvements. Of course this also uses `./postgres/init-reviewboard-db.sh` and `./nginx_templates/default.conf.template`.
```yaml
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=reviewboard
      - POSTGRES_RB_USER=reviewboard
      - POSTGRES_RB_PASSWORD=reviewboard123
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./postgres/init-reviewboard-db.sh:/docker-entrypoint-initdb.d/init-reviewboard-db.sh
    restart: 'on-failure'
  memcached:
    image: memcached:1.6.29-alpine3.20
    restart: 'on-failure'
    entrypoint:
      - memcached
      - -m 128
  reviewboard:
    image: beanbag/reviewboard:7.0.2
    depends_on:
      - db
      - memcached
    environment:
      - DATABASE_TYPE=postgresql
      - COMPANY=Docker Compose Test
      - DATABASE_USERNAME=reviewboard
      - DATABASE_PASSWORD=reviewboard123
      - DOMAIN=localhost
    volumes:
      - site-dir:/site
  nginx:
    image: nginx:1.27.1-alpine3.20
    restart: always
    depends_on:
      - reviewboard
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - "80:80"
    volumes:
      - site-dir:/var/www/reviewboard
      - ./nginx_templates:/etc/nginx/templates
volumes:
  db_data:
  site-dir:
```
- ![image](https://github.com/user-attachments/assets/1bcab191-02b3-4932-95bc-2bbbe1542930)
- Of course I noticed that Review Board 7.0.2 only tested support for `postgres:13-alpine` database. Review Board 7.0.2 does not support the `postgres:16.4-alpine3.20` Docker Image. Is this the reason?
